name: CI
on:
  push:
    branches: [ "El-Fuerte" ]
  pull_request:
    branches: [ "El-Fuerte" ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo El-Fuerte!
