Name: Makoto
SchemaVersion: "1.0"
RunMode: PARALLEL

 Optional - Set automatic triggers. Doing another no-op update
Triggers:
  - Type: Push
    Branches:
      - Makoto
  - Type: PullRequest
    Events:
    - open
    - revision
    Branches:
      - main
Actions:
  Friends:
    Actions:
      A:
        Identifier: aws/build-gamma@v1
        Inputs:
          Sources:
            - WorkflowSource
        Configuration:
          Steps:
            - Run: echo "Makoto!"
      B:
        Identifier: aws/build-gamma@v1
        Inputs:
          Sources:
            - WorkflowSource
        Configuration:
          Steps:
            - Run: echo "Makoto!"
